name: 📦 Create new release

on:
  workflow_run:
    workflows: ["deploy-api-prod"]
    branches: [main]
    # Requied to run only on successful completion of the code-quality workflow
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
